# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Run Automation Harness

on:
  push:
    branches: [main,gnarf-wip]
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'
  pull_request:
    branches: [main]
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
          - 16.x
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
        id: setup-chrome
      - run: |
          echo "Installed chromium version: ${{ steps.setup-chrome.outputs.chrome-version }} ${{ steps.setup-chrome.outputs.chrome-path }}"
      # Installing Scream as a virtual audio driver to avoid this exception installing the sapi
      #
      #
      # npm ERR!   cmd: '"C:\\\\Program Files\\\\Bocoup Automation Voice\\\\Vocalizer.exe"',
      # npm ERR! Unhandled Exception: System.Speech.Internal.Synthesis.AudioException: Audio device error encountered. - Error Code: 0x2
      # npm ERR!    at System.Speech.Internal.Synthesis.VoiceSynthesis.Speak(Prompt prompt)
      # npm ERR!    at System.Speech.Synthesis.SpeechSynthesizer.Speak(Prompt prompt)
      # npm ERR!    at main(String[] args)
      # npm ERR!    at mainCRTStartupStrArray(String[] arguments)
      - name: Install Scream
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - run: npm install -g @bocoup/windows-sapi-tts-engine-for-automation
      - name: Checkout aria-at
        uses: actions/checkout@v3
        with:
          repository: 'w3c/aria-at'
          path: 'aria-at'
      - name: 'aria-at: npm install & build'
        shell: powershell
        run: |
          cd aria-at
          npm install
          npm run build


      - name: Checkout aria-at-automation-harness
        uses: actions/checkout@v3
        with:
          repository: 'w3c/aria-at-automation-harness'
          path: 'automation-harness'
      - name: 'automation-harness: npm install'
        shell: powershell
        run: |
          cd automation-harness
          npm install
      - name: 'patch firefox -> chrome in harness'
        shell: powershell
        run: |
          copy automation-harness/src/agent/web-driver.js webdriver-orig
          Get-Content webdriver-orig | % {$_ -replace "firefox" "chrome" -replace "\xEF\xBB\xBF" "" } | Set-Content automation-harness/src/agent/web-driver.js


      # - uses: nanasess/setup-chromedriver@v2

      - name: Run harness
        run: |
          at-driver *>&1 >at-driver.output &
          chromedriver --port=4444 *>&1 >chromedriver.output &
          nvda-portable\2023.1.0.27913\NVDA.exe *>&1 >nvda.output
          cd aria-at/build/tests/alert
          Start-Sleep -Seconds 10
          echo "--at-driver.output"
          Get-Content -Path ../../../../at-driver.output -ErrorAction Continue
          echo "--chromedriver.output"
          Get-Content -Path ../../../../chromedriver.output -ErrorAction Continue
          echo "--nvda.output"
          Get-Content -Path ../../../../nvda.output -ErrorAction Continue
          node ../../../../automation-harness/bin/host.js run-plan --debug --tests-match 'test-01-trigger-alert*.json' '**/*.html'
          echo "--at-driver.output"
          Get-Content -Path ../../../../at-driver.output -ErrorAction Continue
          echo "--chromedriver.output"
          Get-Content -Path ../../../../chromedriver.output -ErrorAction Continue
          echo "--nvda.output"
          Get-Content -Path ../../../../nvda.output -ErrorAction Continue
