# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'
  pull_request:
    branches: [main]
    paths:
      - '**.js'
      - '**.yml'
      - '**.json'

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
          - 16.x
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Scream
        shell: powershell
        run: |
          Start-Service audio*
          Invoke-WebRequest https://github.com/duncanthrax/scream/releases/download/3.6/Scream3.6.zip -OutFile C:\Scream3.6.zip
          Extract-7Zip -Path C:\Scream3.6.zip -DestinationPath C:\Scream
          $cert = (Get-AuthenticodeSignature C:\Scream\Install\driver\Scream.sys).SignerCertificate
          $store = [System.Security.Cryptography.X509Certificates.X509Store]::new("TrustedPublisher", "LocalMachine")
          $store.Open("ReadWrite")
          $store.Add($cert)
          $store.Close()
          cd C:\Scream\Install\driver
          C:\Scream\Install\helpers\devcon install Scream.inf *Scream
      - run: npm install -g @bocoup/windows-sapi-tts-engine-for-automation
      - run: RUNNER_TRACKING_ID="" && at-driver > /tmp/at-driver.stdout 2> /tmp/at-driver.stderr &
      - run: choco install nvda
      - run: |
          cat /tmp/at-driver.stdout
          cat /tmp/at-driver.stderr
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
